spring:
  h2.console:
    enabled: true
    path: '/console'
  main:
    banner-mode: off
  datasource:
      url: 'jdbc:h2:file:/Users/daro/Downloads/AppTasks/appdb'
  jpa:
    hibernate:
      ddl-auto: create-drop

task:
  template:
    allow-multiple-tasks: false
