spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
      url: 'jdbc:h2:file:/Users/daro/Downloads/SpringAppTasks/appdb'
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
