spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:/Users/daro/Downloads/SpringAppTasks2/appdb'
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  auth-serer-url: 'http://localhost:8180/auth'
  realm: 'AppTasks'
  resource: 'app-tasks-client'
  public-client: true

